config/routes.rb
Gottago::Application.routes.draw do

  resources :bathrooms do
    resources :comments
  end

  get "home/index"

  root :to => 'bathrooms#index'

end

app/models/bathroom.rb
class Bathroom < ActiveRecord::Base
  attr_accessible :building, :cleanliness, :floor, :gender, :notes

  has_many :comments, :dependent => :destroy

  validates_inclusion_of :gender, :in => [ "male", "female" ]
  
  validates :building, :presence => true

  validates :cleanliness, :presence => true,
						:numericality =>
						{
							:only_integer => true,
							:greater_than_or_equal_to => 1,
							:less_than_or_equal_to => 3
						}				

  validates :floor, :presence => true,
  					:numericality =>
  					{
							:only_integer => true,
							:greater_than => 0
						}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :bathroom
  attr_accessible :cleanliness, :comment, :commenter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  # GET /bathrooms
  # GET /bathrooms.json
  def index
    @bathrooms = Bathroom.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bathrooms }
    end
  end

  # GET /bathrooms/1
  # GET /bathrooms/1.json
  def show
    @bathroom = Bathroom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bathroom }
    end
  end

  # GET /bathrooms/new
  # GET /bathrooms/new.json
  def new
    @bathroom = Bathroom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bathroom }
    end
  end

  # GET /bathrooms/1/edit
  def edit
    @bathroom = Bathroom.find(params[:id])
  end

  # POST /bathrooms
  # POST /bathrooms.json
  def create
    @bathroom = Bathroom.new(params[:bathroom])

    respond_to do |format|
      if @bathroom.save
        format.html { redirect_to @bathroom, notice: 'Bathroom was successfully created.' }
        format.json { render json: @bathroom, status: :created, location: @bathroom }
      else
        format.html { render action: "new" }
        format.json { render json: @bathroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bathrooms/1
  # PUT /bathrooms/1.json
  def update
    @bathroom = Bathroom.find(params[:id])

    respond_to do |format|
      if @bathroom.update_attributes(params[:bathroom])
        format.html { redirect_to @bathroom, notice: 'Bathroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bathroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bathrooms/1
  # DELETE /bathrooms/1.json
  def destroy
    @bathroom = Bathroom.find(params[:id])
    @bathroom.destroy

    respond_to do |format|
      format.html { redirect_to bathrooms_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @bathroom = Bathroom.find(params[:bathroom_id])
    @comment = @bathroom.comments.create(params[:comment])

    redirect_to bathroom_path(@bathroom)
  end

  def update
    @bathroom = Bathroom.find(params[:bathroom_id])
    @comment = @bathroom.comments.find(params[:comment_id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @bathroom = Bathroom.find(params[:bathroom_id])
    @comment = @bathroom.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to bathroom_path(@bathroom) }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bathrooms_helper.rb
module BathroomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bathrooms/_form.html.erb
<%= form_for(@bathroom) do |f| %>
  <% if @bathroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bathroom.errors.count, "error") %> prohibited this bathroom from being saved:</h2>

      <ul>
      <% @bathroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :building %><br />
    <%= f.text_field :building %>
  </div>
  <div class="field">
    <%= f.label :floor %><br />
    <%= f.number_field :floor %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.radio_button :gender, "male" %>
    <%= f.label :gender_male, "Male" %>
    <%= f.radio_button :gender, "female" %>
    <%= f.label :gender_female, "Female" %>
  </div>
  <div class="field">
    <%= f.label :cleanliness %>
    <%= f.radio_button :cleanliness, "1" %>
    <%= f.label :cleanliness_1, "Bad" %>
    <%= f.radio_button :cleanliness, "2" %>
    <%= f.label :cleanliness_2, "Average" %>
    <%= f.radio_button :cleanliness, "3" %>
    <%= f.label :cleanliness_3, "Good" %>
  </div>
  <div class="field"3
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bathrooms/edit.html.erb
<h1>Editing bathroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @bathroom %> |
<%= link_to 'Back', bathrooms_path %>

app/views/bathrooms/index.html.erb
<h1>Gotta Go</h1>
<h2>Listing bathrooms</h2>

<table>
  <tr>
    <th>Building</th>
    <th>Floor</th>
    <th>Gender</th>
    <th>Cleanliness</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bathrooms.each do |bathroom| %>
  <tr>
    <td><%= bathroom.building %></td>
    <td><%= bathroom.floor %></td>
    <td><%= bathroom.gender.to_s.capitalize %></td>
    <td><%= bathroom.cleanliness %></td>
    <td><%= bathroom.notes %></td>
    <td><%= link_to 'Show', bathroom %></td>
    <td><%= link_to 'Edit', edit_bathroom_path(bathroom) %></td>
    <td><%= link_to 'Destroy', bathroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bathroom', new_bathroom_path %>

app/views/bathrooms/new.html.erb
<h1>New bathroom</h1>

<%= render 'form' %>

<%= link_to 'Back', bathrooms_path %>

app/views/bathrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Building:</b>
  <%= @bathroom.building %>
</p>

<p>
  <b>Floor:</b>
  <%= @bathroom.floor %>
</p>

<p>
  <b>Gender:</b>
  <%= @bathroom.gender.to_s.capitalize %>
</p>

<p>
  <b>Cleanliness:</b>
  <%= @bathroom.cleanliness %>
</p>

<p>
  <b>Notes:</b>
  <%= @bathroom.notes %>
</p>

<h2>Comments</h2>
<% if @bathroom.comments.empty? %>
  <p>No comments found.</p>
<% end %>
<%= render @bathroom.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit', edit_bathroom_path(@bathroom) %> |
<%= link_to 'Back', bathrooms_path %>

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>

<p>
  <b>Cleanliness:</b>
  <%= comment.cleanliness %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.comment %>
</p>
<p>
  <%= link_to 'Delete Comment', [comment.bathroom, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@bathroom, @bathroom.comments.build]) do |f| %>
  <% if @bathroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bathroom.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @bathroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :your_name %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :cleanliness %>
    <%= f.radio_button :cleanliness, "1" %>
    <%= f.label :cleanliness_1, "Bad" %>
    <%= f.radio_button :cleanliness, "2" %>
    <%= f.label :cleanliness_2, "Average" %>
    <%= f.radio_button :cleanliness, "3" %>
    <%= f.label :cleanliness_3, "Good" %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Commentor</th>
    <th>Cleaniness</th>
    <th>Comment</th>
    <th>Bathroom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.commentor %></td>
    <td><%= comment.cleaniness %></td>
    <td><%= comment.comment %></td>
    <td><%= comment.bathroom %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Commentor:</b>
  <%= @comment.commentor %>
</p>

<p>
  <b>Cleaniness:</b>
  <%= @comment.cleaniness %>
</p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>

<p>
  <b>Bathroom:</b>
  <%= @comment.bathroom %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<h1>Gotta Go...?</h1>
<%= link_to "Bathroom List", bathrooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset = utf-8>
  <title>Because you Gotta Go -- Find and rate bathrooms near you</title>
  <%= stylesheet_link_tag    "http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css", :media => "all" %>
  <%= javascript_include_tag "application", "http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"/>
</head>
<body>
<%= yield %>

</body>
</html>